baseURL = 'https://geekclub.dk/'
languageCode = 'en-us'
title = 'Geekclub'

theme = "vintage-web-hugo-theme"

# Pagination
[pagination]
  pagerSize = 10
  path = "page"

# Taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# Menu
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 20

[[menu.main]]
  name = "Om"
  url = "/om/"
  weight = 30

# Theme Parameters
[params]
  # Site Description
  description = "Hvor geeks mødes"
  author = "Geekclub"

  # Retro Features
  show_browser_chrome = true
  show_status_bar = true
  show_sidebar = true
  show_welcome_message = true
  welcome_message = "Velkommen til Geekclub"

  # Content Display
  show_featured_sections = true
  show_stats = true
  show_retro_elements = true
  show_sharing = true

  # Footer Options
  show_retro_footer = true
  show_build_info = false

  # Sidebar Options
  show_sidebar_stats = true
  show_retro_sidebar = true
  sidebar_content = "Velkommen til Geekclub"

  # Social Links
  #[params.social]
  #  twitter = "username"
  #  github = "username"
  #  linkedin = "username"
  #  email = "you@example.com"
  #  mastodon = "https://mastodon.social/@username"
  #  youtube = "channelname"
  #  instagram = "username"

  # Repository (for edit links)
  repo_url = "https://github.com/geekclubdk/geekclubdk.github.io"
  edit_page = false
